# Generated by Django 5.0 on 2023-12-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="staff_Ret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User", models.CharField(max_length=30)),
                ("book", models.CharField(max_length=30)),
                ("BookName", models.CharField(max_length=50)),
                ("BookNo", models.CharField(max_length=30)),
                ("IssueDate", models.DateField()),
                ("RetDate", models.DateField()),
                ("Fine", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="staff_select",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User", models.CharField(max_length=30)),
                ("book", models.CharField(max_length=30)),
                ("BookNo", models.IntegerField()),
                ("Image", models.ImageField(upload_to="images")),
                ("BookName", models.CharField(max_length=50)),
                ("Category", models.CharField(max_length=50)),
                ("Author", models.CharField(max_length=50)),
                ("Publisher", models.CharField(max_length=50)),
                ("Return", models.IntegerField()),
                ("Date", models.DateField(max_length=50)),
                ("Fine", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="stud_select",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User", models.CharField(max_length=30)),
                ("book", models.CharField(max_length=30)),
                ("BookNo", models.IntegerField()),
                ("Image", models.ImageField(upload_to="images")),
                ("BookName", models.CharField(max_length=50)),
                ("Category", models.CharField(max_length=50)),
                ("Author", models.CharField(max_length=50)),
                ("Publisher", models.CharField(max_length=50)),
                ("Return", models.IntegerField()),
                ("Date1", models.CharField(max_length=30)),
                ("Fine", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SName", models.CharField(max_length=30)),
                ("StPhone", models.IntegerField()),
                ("role", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BookNo", models.IntegerField()),
                ("Image", models.ImageField(upload_to="images")),
                ("BookName", models.CharField(max_length=50)),
                ("Category", models.CharField(max_length=50)),
                ("Author", models.CharField(max_length=50)),
                ("Publisher", models.CharField(max_length=50)),
                ("Return", models.IntegerField()),
                ("Fine", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SDName", models.CharField(max_length=30)),
                ("SDPhone", models.IntegerField()),
                ("role", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
