# Generated by Django 5.0 on 2023-12-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_ret",
            name="Fine",
            field=models.IntegerField(),
        ),
    ]
