# Generated by Django 5.0 on 2023-12-13 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlib", "0002_alter_staff_ret_fine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff_ret",
            old_name="User",
            new_name="user",
        ),
    ]
