# Generated by Django 5.0 on 2023-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlib", "0003_rename_user_staff_ret_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_ret",
            name="IssueDate",
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name="staff_ret",
            name="RetDate",
            field=models.DateField(max_length=30),
        ),
    ]
