# Generated by Django 5.0 on 2023-12-14 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlib", "0004_alter_staff_ret_issuedate_alter_staff_ret_retdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff_ret",
            old_name="IssueDate",
            new_name="Date",
        ),
    ]
