# Generated by Django 5.0 on 2023-12-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlib", "0005_rename_issuedate_staff_ret_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_ret",
            name="Date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="staff_ret",
            name="RetDate",
            field=models.DateField(),
        ),
    ]
